PROGRAM PrintHello(INPUT, OUTPUT);
USES
  DOS;
BEGIN
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN('Hello, World');
  WRITELN('REQUEST_METHOD');
  WRITELN('QUERY_STRING');
  WRITELN('CONTENT_LENGTH');
  WRITELN('HTTP_USER_AGENT');
  WRITELN('HTTP_HOST')
END.

